language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

install:
  - "pip install --upgrade pip"
  - "pip install -r requirements_all.txt"
  - "pip install coveralls"

script: coverage run tests/testsuite.py

after_success:
  coveralls
